### ISSUE TITLE
On windows, extension can start with cmd instead of powershell shell in terminal. This results in PDK not working

### ISSUE THREAD

**Issue by dan-wittenberg** [lingua-pupuli/puppet-vscode#152]
VScode can be started with an integrated shell of cmd instead of powershell, which will cause the 'pdk ...' commands to run but it will complain that it can't find the command.

**Comment by jpogran** [comment]
In the ensuing time, VSCode has enabled the ability to set the default terminal which will be [opened](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows). In order to make sure VSCode uses PowerShell, open up the User Settings and ensure the following is set:

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

Also, you can ensure that PowerShell is used for any exec commands by setting:

```
"terminal.external.windowsExec": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
 ```
