### ISSUE TITLE
vscode lint not working

### ISSUE THREAD

**Issue by lanox** [lingua-pupuli/puppet-vscode#261]
### What Versions are you running?

OS Version: 10.13.4
VSCode Version:1.22.2
Puppet Extension Version:0.10.0
Puppet Agent Version: v5.5.0
PDK Version (if applicable):1.4.1

### What You Are Seeing?
Linting doesn't seem to be working 

class influxdb::params {
  $admin_enable            = false
  $admin_bind_address      = '0.0.0.0:8083'
  $domain_name             = undef
  $http_enable             = true
  $http_bind_address       = '0.0.0.0:8086'
}
### What is Expected?
```
class influxdb::params {
  $admin_enable            = false
  $admin_bind_address      = '0.0.0.0:8083'
  $domain_name             = undef
  $http_enable             = true
  $http_bind_address       = '0.0.0.0:8086'
}
```
### How Did You Get This To Happen? (Steps to Reproduce)
Installed vscode plugin, then installed puppet agent using brew cask and pdk as well.

**Comment by glennsarti** [comment]
Hi @lanox ,

Can you describe what doesn't seem to be working in a little more detail? e.g. what lint errors were you expecting?

**Comment by lanox** [comment]
Hi

Listing doesn’t seem to be aligning = or => or complaining. 
Basically I think my lint is not working in vscode.

**Comment by glennsarti** [comment]
Puppet Lint doesn't seem to enforce indenting, unless it's consistent..  e.g.

``` puppet
class influxdb::params {
$admin_enable = false
$admin_bind_address = '0.0.0.0:8083'
$domain_name = undef
   $http_enable = true
$http_bind_address = '0.0.0.0:8086'
}
```
should show a lint error

**Comment by glennsarti** [comment]
Looks look it accepts 0,2,4,6.... space indenting.

**Comment by lanox** [comment]
Sorry I am out at the moment so I can’t test it,  so is that normal or a bug ?

**Comment by glennsarti** [comment]
This sounds like a bug in puppet-lint.

**Comment by glennsarti** [comment]
Raised https://github.com/rodjek/puppet-lint/issues/822 to track the issue.

**Comment by glennsarti** [comment]
@lanox You happy for me to close this issue as it's being tracked via puppet-lint?

**Comment by br0ch0n** [comment]
for me, it complains about alignment of hash rockets in the "Problems" window but doesn't complain about regular equals signs.  Equals signs are probably a problem with puppet-lint.  For the hash rockets, should they be auto-aligning instead of just getting underlined and complaining?  Or is it not expected to auto correct such things as you type (or is that an option I haven't enabled)?

**Comment by glennsarti** [comment]
@br0ch0n Slightly different issue but....

The problems window only shows issues.  We can't do per-problem resolution because puppet-lint can only fix an entire document at a time.  To that end though, If you use the "Format Document" VS code command it will apply any fixes puppet-lint makes. (https://code.visualstudio.com/docs/editor/codebasics#_formatting)

Also means you can take advantage of the 'editor.formatOnSave' setting and automatically apply any puppet-lint fixes after you save a document :-)

We added that in 0.9.0 (https://github.com/lingua-pupuli/puppet-vscode/commit/97897aa27d6658b5f37a8d92a6a019a0b7fcb72a)

**Comment by jpogran** [comment]
I'm closing this issue as it's being tracked in the puppet-lint project.
