### ISSUE TITLE
Issue during startup

### ISSUE THREAD

**Issue by rrod157** [lingua-pupuli/puppet-vscode#329]
Hello,

When I startup VS code today, I noticed this error appear on my lower right notification:

Could not find a valid Puppet installation at 'C:\Program Files\Puppet Labs\Puppet\puppet'. While syntax highlighting and grammar detection will still work, intellisense and other advanced features will not.

**Comment by jpogran** [comment]
HI @rrod157 that error means that the extension could not find the Puppet Agent installed on your machine. As we state in the [readme](https://github.com/lingua-pupuli/puppet-vscode/blob/master/README.md#requirements) that shows up in the VSCode gallery, we need Puppet Agent installed in order to enable the more advanced features the extension has.

The error message should have pointed you [here](https://github.com/lingua-pupuli/puppet-vscode/blob/master/README.md#experience-a-problem) which has more explanation and some troubleshooting steps. Please reply back if that does not help.

**Comment by rrod157** [comment]
Thanks. It seem to work fine now.

Regards,
Rustan Rodriguez
Middleware Engineer
Application Infrastructure Services - Manila
m: +63-917-862-7097 | page-Rustan.Rodriguez@safeway.com | Infra.Services.Middleware.Services@safeway.com
