### ISSUE TITLE
Show Progress

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-vscode#445]
## Indicating Progress

When the Puppet Extension starts, it starts the Puppet Language Server (LS) in the background while leaving the editor to be used immediately. The LS is slow to load compared to VSCode, but functionality can be used as it loads. To indicate what functionality is available we have the following animation and tooltip:

![original](https://user-images.githubusercontent.com/272569/49816928-f2e8ac80-fd3c-11e8-92ba-4a1ed5b25d2c.gif)

It works and provides the information necessary to determine what advanced features are ready for use, but if you don't know to hover you never 'see' the information. There are other notification mechanisms in VSCode we can use to show progress, with varying options.

## Proposed Progress Options

1. The first is a progress window. It pops a `info` window that does not steal focus, and has a progress bar that fills to indicate how far along its loaded. The text is updated as each portion is loaded, with minimal styling allowed (no newlines but emojis and spaces allowed, etc). It also provides an ability to cancel loading, but we will likely not implement at first, if at all. It disappears by itself when done, and we can add a setting to disable progress for advanced users who don't want the window pop or think it annoying.

![withprogress](https://user-images.githubusercontent.com/272569/49817128-74d8d580-fd3d-11e8-94a7-136f66ce5203.gif)

2. We can also use the main VSCode window to show the same information without a popup. Note that the newlines truncate the displayed info but is shown on hover. This means it's still shown on small screens, but isn't very informative without hovering over.

![inwindow](https://user-images.githubusercontent.com/272569/49817603-b1f19780-fd3e-11e8-8c24-7af5635b7cc1.gif)

3.  If we remove the newlines the information is now constantly visible but in a non-annoying part of the screen. Great for at a glance information, but also easily ignorable. However we need a wider window to see the information, or else it is not shown and you can't hover over it.

![inwindownonewlines](https://user-images.githubusercontent.com/272569/49817421-2841ca00-fd3e-11e8-98fd-a0c753ed5cd0.gif)

So which do you like?

**Comment by hlindberg** [comment]
Can you give a hint that it is worth hovering? If it was a webpage, if something is underlined you know it is a link and you may hover over it... Or maybe have an icon that looks like a button so you think you can click - as user moves there the popup appears. I think which one is best depends on if a user wants to wait for one particular thing to be loaded before continuing then the longer forms may be a better option (e.g. 1).

Just my 2c.

**Comment by jpogran** [comment]
@hlindberg thanks for the feedback. The statusbar is intentionally minimalist by design and so you can't change appearances much, and it all has to respect the theme chosen by the user. Even though the icon in the lower right hand corner is a button, I can't make it any different than it already is (i.e. a green turning circle or a terminal icon). We do call out that you can hover for this information in the README, but it's not very discoverable there when you're using the editor.

The above approaches were the attempt to do what you suggest, do something that was more of a hint without being obtrusive or annoying.

**Comment by jpogran** [comment]
I've reworked the approach and now have a solution that does...all of the above. I add a new configuration setting called `showLoadProgressWindow`, that accepts an enum of `popup`, `integrated`, and `off'. Depending on the selection, any of the above approaches will be triggered.

**Comment by glennsarti** [comment]
Would an additional option be  ... re-introduce the percentage indicator again? (I still prefer the spinning icon :-) )

**Comment by TJM** [comment]
I prefer the spinning circle with hover (current way) with some modification, see below. 

I like the idea of a percentage, if that is reasonable to calculate. It should not just be 25,50,75,100 based on the 4 components,  rather an estimate of time based percentage complete. It appears, based on the second option with a progress bar, that it may be possible?

Honestly, I think you are probably putting too much effort into what partial service is available. Does anyone really think, oh good, now that facts are loaded, I can edit this file? They are either completely oblivious, or don't care that anything is even loading or they wait till its complete. I will have to test on my "Symantec Infested" windows computer tomorrow, but on my 5+ year old Macs it takes less than one second to load currently. It is actually hard to even get the hover to come up because it is done so quick.

In my opinion, the text should read something like `(CIRCLE) Puppet Language Server Loading (xx%) ...` or maybe just 'Puppet LS Loading (xx%) ...` instead of just "X.Y.Z" (version). To me the "..." indicates there is more information, but I am no UI/UX expert. There is a UI/UX area in stack overflow, I think. On "hover" it should pop up the loading dialog like it does currently, but with a header (or at least first line) `Puppet Language Server vX.Y.Z`. Once the loading is complete, the text should change to `(ICON) X.Y.Z` like it does now.

If we have to change, I would vote for the first option (info window). I personally do not like option 2 or 3.

**Comment by glennsarti** [comment]
Shall we close this @jpogran?
